### ISSUE TITLE
Using this mod crashes the game

### ISSUE THREAD

**Issue by syrupderg** [Blayung/allow-portal-guis#1]
![image](https://github.com/Blayung/allow-portal-guis/assets/67545942/c981568b-fbcb-4083-bc2d-9280b0e6a2ef)

Error log: 
[crash.txt](https://github.com/Blayung/allow-portal-guis/files/14244897/crash.txt)

**Comment by Blayung** [comment]
Oh shit, I did one thing wrong. I'm going to fix it as soon as I'm home. For now, you could simply use the previous version of the mod.

**Comment by Blayung** [comment]
I've deleted the version with the error from modrinth, you can download the latest one again.

**Comment by Blayung** [comment]
Okay, now there's a new release with a fix (1.0.5)
